% ---------------------------------------------------------------------
\title{Brain Visualization - STAR Report}

% for anonymous conference submission please enter your SUBMISSION ID
% instead of the author's name (and leave the affiliation blank) !!
\author[M. Konefal \& M. Wiedhalm]
       {M. Konefał$^{1}$
        and M. Wiedhalm$^{1}$
        \\
         $^1$Group 15\\
       }

% ------------------------------------------------------------------------


\begin{document}


\maketitle

\begin{abstract}


\end{abstract}



%-------------------------------------------------------------------------
\section{Instructions}

Brain is our most important organ\cite{Murre-Sturdy95}. It is complicated nervous system which controlls most of activities in our body and play key part in human cognition. This organ could not be replaced and its function could not be artificially taken over, consequentlly any damage or serious patology change could put at risk whole organism.

%-------------------------------------------------------------------------
\subsection{Responsibilities}

Marcin Konefał worked on:
\begin{itemize}
\item Preperation of latex file
\item Section - Introduction
\item Section - Human Connectome Project
\end{itemize}


%-------------------------------------------------------------------------
\bibliography{egbibsample}
\bibliographystyle{eg-alpha}
%\bibliographystyle{eg-alpha-doi}

\end{document}
